#!/usr/bin/env bash

MAKOCONFIG="$HOME/.config/mako/config"
COLORS="$HOME/.cache/wal/colors"

COLOR0=`head -1 $COLORS`
COLOR1=`head -2 $COLORS | tail -1`
COLOR2=`head -3 $COLORS | tail -1`
COLOR3=`head -4 $COLORS | tail -1`
COLOR4=`head -5 $COLORS | tail -1`
COLOR5=`head -6 $COLORS | tail -1`
COLOR6=`head -7 $COLORS | tail -1`

cat << EOF > $MAKOCONFIG
layer=overlay
anchor=top-right
width=300
padding=6
margin=4
border-size=2
border-radius=0
default-timeout=5000
icons=1
max-icon-size=64

background-color=$COLOR0
text-color=$COLOR1

[urgency=low]
border-color=$COLOR6
text-color=$COLOR5
default-timeout=3000

[urgency=normal]
border-color=$COLOR6
text-color=$COLOR5
default-timeout=10000
ignore-timeout=1

[urgency=high]
border-color=$COLOR2
text-color=$COLOR6
default-timeout=0
ignore-timeout=1
EOF

makoctl  reload